export const FAKE_PLAYER_ROLES = {
  fake_player_01: "Tank",
  fake_player_02: "Dps",
  fake_player_03: "Rdps",
  fake_player_04: "Debuffer",
  fake_player_05: "Dps",
  fake_player_06: "Tank",
  fake_player_07: "Dps",
  fake_player_08: "Rdps",
  fake_player_09: "Debuffer",
  fake_player_10: "Dps",
  fake_player_11: "Tank",
  fake_player_12: "Dps",
  fake_player_13: "Rdps",
  fake_player_14: "Debuffer",
  fake_player_15: "Dps",
  fake_player_16: "Tank",
  fake_player_17: "Dps",
  fake_player_18: "Rdps",
  fake_player_19: "Debuffer",
  fake_player_20: "Dps",
  fake_healer_01: "Healer",
  fake_healer_02: "Healer"
};
